- name: copy elastic Yum repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install file beat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: file beat configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: start file beat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes

