#- name: logstash config copy
#  ansible.builtin.template:
#    src: logstash.conf
#    dest: /etc/logstash/conf.d/logstash.conf
#
#- name: Restart logstash
#  ansible.builtin.systemd:
#    name: logstash
#    state: restarted
#    enabled: yes

- name: Load logstash
  ansible.builtin.include_tasks: logstash.yml
  when: elk_component == "logstash"

- name: Load filebeat
  ansible.builtin.include_tasks: filebeat.yml
  when: elk_component == "filebeat"