- name: logstash config copy
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart logstash
  ansible.builtin.template:
    name: logstash
    state: restarted
    enabled: yes